name: 'Entrance/Exit Check-in'
description: 'Runs a docker image with the entrance/exit operations'
inputs:
  cypress-arguments:
    description: 'Arguments passed to Cypress CLI'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '--browser chrome'
    - ${{ inputs.cypress-arguments }}
