name: "entrance-automation"
on:
  repository_dispatch:
    types:
      - entrance_automation
jobs:
  automation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache register
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile') }}
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          load: true
          tags: entrance_automation:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Run Docker container
        run: |
          echo $USERNAME && \
          docker run -it --rm \
            -e USERNAME=${{ secrets.PORTAL_USERNAME }} \
            -e PASSWORD=${{ secrets.PORTAL_PASSWORD }} \
            -e LOGIN_URL=${{ secrets.PORTAL_LOGIN_URL }} \
            entrance_automation:latest \
            --spec=cypress/integration/presence-entrance.spec.js

#      - name: Entrance Check-in
#        uses: ./
#        with:
#          cypress-arguments: '--spec=cypress/integration/presence-entrance.spec.js'
#        env:
#          USERNAME: ${{ secrets.PORTAL_USERNAME }}
#          PASSWORD: ${{ secrets.PORTAL_PASSWORD }}
#          LOGIN_URL: ${{ secrets.PORTAL_LOGIN_URL }}
