name: "exit-automation"
on:
  repository_dispatch:
    types:
      - exit_automation
jobs:
  automation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Random Sleep
        run: sleep $(shuf -i 1-240 -n 1)
      - name: Checkout
        uses: actions/checkout@v2
      - name: Exit Check-in
        uses: ./
        with:
          cypress-arguments: '--spec=cypress/integration/presence-exit.spec.js'
        env:
          USERNAME: ${{ secrets.PORTAL_USERNAME }}
          PASSWORD: ${{ secrets.PORTAL_PASSWORD }}
          LOGIN_URL: ${{ secrets.PORTAL_LOGIN_URL }}
      - name: Send Telegram OK message
        if: ${{ success() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO_SUCCESS }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Check-in for Exit have been successfully completed.
      - name: Send Telegram KO message
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO_FAILURE }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            OUCH! Your check-in for Exit have just FAILED :(
